backend:
  name: github
  repo: oeroglu/flight-check
  branch: main

local_backend: true

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "routes"
    label: "Routes"
    files:
      - file: "routes/routes.json"
        label: "Flight Routes"
        name: "routes"
        format: "json"
        fields:
          - label: "Routes"
            name: "routes"
            widget: "list"
            fields:
              - { label: "Origin", name: "origin", widget: "string" }
              - { label: "Destination", name: "destination", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
              - { label: "Max Price", name: "max_price", widget: "number" }
              - { label: "Active", name: "active", widget: "boolean", default: true }
