backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

locale: "tr"

publish_mode: simple

collections:
  - name: "routes"
    label: "Routes"
    files:
      - file: "routes/routes.json"
        label: "Flight Routes"
        name: "routes"
        format: "json"
        fields:
          - name: "routes"
            widget: "list"
            fields:
              - { name: "origin", widget: "string" }
              - { name: "destination", widget: "string" }
              - { name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
              - { name: "max_price", widget: "number", value_type: "int", min: 0 }
              - { name: "active", widget: "boolean", default: true }
